import { StoreTaskOperation, StoreTaskOperationProcessingRound } from '../operation';
import { OperationFactory } from './operation-factory';

export class OctraOperation extends StoreTaskOperation<any> {

}

export class OctraOperationFactory extends OperationFactory<OctraOperation> {
  protected readonly _description =
    'A literal transcript contains the verbatim text of a speech recording.' +
    'These transcripts are either generated by Automatic Speech Recognition or they are created manually from scratch.' +
    'The editor Octra allows you to correct or create such transcripts.';
  protected readonly _name = 'OCTRA';
  protected readonly _resultType = 'BAS Partitur Format';
  protected readonly _shortTitle = 'MT';
  protected readonly _title = 'Manual Transcription';

  create(id: number, taskID: number, rounds: StoreTaskOperationProcessingRound[]): OctraOperation {
    return new OctraOperation({
      enabled: true,
      id,
      mouseOver: false,
      name: '',
      options: {},
      rounds,
      taskID,
    });
  }
}
